- hosts: all
  become: yes
  roles:
    - roles/initial

- hosts: all
  become: yes
  roles:
    - roles/kube-dependencies

- hosts: master
  become: yes
  roles:
    - roles/kubectl

- hosts: master
  become: yes
  roles:
    - roles/master

- hosts: workers
  become: yes
  roles:
    - roles/workers

- hosts: master
  become: yes
  become_user: ubuntu
  #remote_user: ubuntu
  roles:
    - roles/nginx

